version: "3"

networks:
  zoomcamp:
    name: zoomcamp_network

services:
  postgres:
    image: postgres:13
    container_name: postgres_zoomcamp
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ./ny_taxi_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zoomcamp
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_zoomcamp
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - zoomcamp

  kestra:
    image: kestra/kestra:latest
    container_name: kestra_zoomcamp
    command: server local
    ports:
      - "8081:8080"
    networks:
      - zoomcamp
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          server:
            basic-auth:
              enabled: false
    depends_on:
      postgres:
        condition: service_healthy